"use client";

import React, { useState, useEffect, useRef } from "react";
import { X, ShieldAlert, Check, Sparkles } from "lucide-react";
import { useApp } from "@/context/AppContext";

interface JoinHouseholdSheetProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function JoinHouseholdSheet({ isOpen, onClose }: JoinHouseholdSheetProps) {
  const { joinHousehold } = useApp();
  const [codeValue, setCodeValue] = useState("");
  const [isJoining, setIsJoining] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [isSuccess, setIsSuccess] = useState(false);

  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isOpen) {
      setCodeValue("");
      setErrorMsg("");
      setIsSuccess(false);
      // Auto focus with a small delay for animation readiness
      const timer = setTimeout(() => {
        inputRef.current?.focus();
      }, 150);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value.replace(/[^A-Za-z0-9]/g, "").slice(0, 6).toUpperCase();
    setCodeValue(raw);
    setErrorMsg("");
  };

  const getDisplayValue = () => {
    if (codeValue.length > 3) {
      return `${codeValue.slice(0, 3)}-${codeValue.slice(3)}`;
    }
    return codeValue;
  };

  const handleJoin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (codeValue.length !== 6) {
      setErrorMsg("Please enter a valid 6-digit code.");
      return;
    }

    setIsJoining(true);
    setErrorMsg("");
    try {
      await joinHousehold(codeValue);
      setIsSuccess(true);
      // Wait for the success animation before closing and redirecting
      setTimeout(() => {
        onClose();
        // Redirect to dashboard (handled by routing state reload)
        window.location.href = "/";
      }, 1500);
    } catch (err: any) {
      console.error("Error joining household:", err);
      const msg = err.message || "";
      if (msg.includes("expired")) {
        setErrorMsg("Code expired. Please generate a new code.");
      } else if (msg.includes("already a member")) {
        setErrorMsg("You are already a member of this household.");
      } else if (msg.includes("Invalid")) {
        setErrorMsg("Invalid code. Please check and try again.");
      } else {
        setErrorMsg(msg || "Failed to join household.");
      }
    } finally {
      setIsJoining(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[110] flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-in fade-in duration-200">
      {/* Backdrop overlay click */}
      {!isJoining && !isSuccess && (
        <div className="absolute inset-0" onClick={onClose} />
      )}

      {/* Centered Modal Content */}
      <div className="relative w-full max-w-sm bg-[#111111] border border-white/10 rounded-2xl p-6 flex flex-col shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-250">
        
        {/* Close Button */}
        {!isJoining && !isSuccess && (
          <button
            onClick={onClose}
            className="absolute top-4 right-4 rounded-full p-1.5 text-muted hover:bg-white/5 hover:text-foreground transition-colors focus:outline-none focus:ring-1 focus:ring-primary/50"
          >
            <X size={16} />
          </button>
        )}

        {isSuccess ? (
          <div className="flex flex-col items-center justify-center py-8 space-y-4 animate-in zoom-in-95 duration-300">
            <div className="h-16 w-16 rounded-full bg-primary/20 flex items-center justify-center text-[#c8ff00] border border-primary/30 shadow-[0_0_20px_rgba(200,255,0,0.2)]">
              <Check size={32} className="animate-bounce" />
            </div>
            <h3 className="font-syne font-bold text-lg text-white text-center">
              Successfully Joined!
            </h3>
            <p className="text-xs text-muted text-center font-sans max-w-xs">
              Setting up your workspace dashboard...
            </p>
          </div>
        ) : (
          <form onSubmit={handleJoin} className="space-y-6">
            <div className="text-center space-y-1.5 pt-2">
              <div className="mx-auto h-12 w-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center text-[#c8ff00] mb-2">
                <Sparkles size={20} />
              </div>
              <h2 className="font-syne font-bold text-lg text-white">
                Join a Household
              </h2>
              <p className="text-xs text-muted font-sans max-w-xs mx-auto">
                Enter the 6-digit invitation code generated by the household owner.
              </p>
            </div>

            {/* Input Code */}
            <div className="space-y-2">
              <div className="relative">
                <input
                  ref={inputRef}
                  type="text"
                  pattern="[A-Za-z0-9-]*"
                  inputMode="text"
                  placeholder="ABC-123"
                  value={getDisplayValue()}
                  onChange={handleInputChange}
                  disabled={isJoining}
                  className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl px-4 py-3 text-center font-mono text-xl font-bold tracking-widest text-[#c8ff00] focus:ring-2 focus:ring-primary/40 focus:border-primary outline-none transition-all uppercase placeholder:text-zinc-700"
                />
              </div>

              {errorMsg && (
                <div className="flex items-center gap-2 text-xs font-semibold text-[#ff3d57] font-sans justify-center bg-[#ff3d57]/10 p-2.5 rounded-lg border border-[#ff3d57]/20">
                  <ShieldAlert size={14} className="shrink-0" />
                  <span>{errorMsg}</span>
                </div>
              )}
            </div>

            {/* Action buttons */}
            <div className="flex items-center gap-3">
              <button
                type="button"
                onClick={onClose}
                disabled={isJoining}
                className="flex-1 py-3 rounded-xl border border-white/10 text-xs font-bold text-muted hover:text-foreground hover:bg-white/5 transition-all cursor-pointer"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isJoining || codeValue.length !== 6}
                className="flex-1 py-3 bg-[#c8ff00] text-black font-bold rounded-xl text-xs uppercase tracking-wider hover:brightness-110 active:scale-95 transition-all disabled:opacity-40 disabled:pointer-events-none cursor-pointer flex items-center justify-center gap-1.5"
              >
                {isJoining ? "Joining..." : "Join"}
              </button>
            </div>
          </form>
        )}
      </div>
    </div>
  );
}
