"use client";

import React, { useState, useEffect, useRef } from "react";
import { ShieldAlert, Check, Sparkles } from "lucide-react";
import { useApp } from "@/context/AppContext";
import Dialog, { DialogButton } from "@/components/ui/Dialog";

interface JoinHouseholdSheetProps {
  isOpen: boolean;
  onClose: () => void;
}

export default function JoinHouseholdSheet({ isOpen, onClose }: JoinHouseholdSheetProps) {
  const { joinHousehold } = useApp();
  const [codeValue, setCodeValue] = useState("");
  const [isJoining, setIsJoining] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [isSuccess, setIsSuccess] = useState(false);

  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isOpen) {
      setCodeValue("");
      setErrorMsg("");
      setIsSuccess(false);
      // Auto focus with a small delay for animation readiness
      const timer = setTimeout(() => {
        inputRef.current?.focus();
      }, 150);
      return () => clearTimeout(timer);
    }
  }, [isOpen]);

  if (!isOpen) return null;

  // While joining or showing success, block all close paths (Escape,
  // backdrop, X) — Dialog always allows Escape/backdrop otherwise, so we
  // pass a no-op onClose and hide the X for the in-flight window.
  const inFlight = isJoining || isSuccess;

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const raw = e.target.value.replace(/[^A-Za-z0-9]/g, "").slice(0, 6).toUpperCase();
    setCodeValue(raw);
    setErrorMsg("");
  };

  const getDisplayValue = () => {
    if (codeValue.length > 3) {
      return `${codeValue.slice(0, 3)}-${codeValue.slice(3)}`;
    }
    return codeValue;
  };

  const handleJoin = async (e: React.FormEvent) => {
    e.preventDefault();
    if (codeValue.length !== 6) {
      setErrorMsg("Please enter a valid 6-digit code.");
      return;
    }

    setIsJoining(true);
    setErrorMsg("");
    try {
      await joinHousehold(codeValue);
      setIsSuccess(true);
      // Wait for the success animation before closing and redirecting
      setTimeout(() => {
        onClose();
        // Redirect to dashboard (handled by routing state reload)
        window.location.href = "/";
      }, 1500);
    } catch (err: any) {
      console.error("Error joining household:", err);
      const msg = err.message || "";
      if (msg.includes("expired")) {
        setErrorMsg("Code expired. Please generate a new code.");
      } else if (msg.includes("already a member")) {
        setErrorMsg("You are already a member of this household.");
      } else if (msg.includes("Invalid")) {
        setErrorMsg("Invalid code. Please check and try again.");
      } else {
        setErrorMsg(msg || "Failed to join household.");
      }
    } finally {
      setIsJoining(false);
    }
  };

  return (
    <Dialog
      open={isOpen}
      onClose={inFlight ? () => {} : onClose}
      hideClose={inFlight}
      maxWidthClass="max-w-sm"
      title={isSuccess ? "Successfully Joined!" : "Join a Household"}
      icon={
        isSuccess ? (
          <Check size={20} className="text-primary" />
        ) : (
          <Sparkles size={20} className="text-primary" />
        )
      }
      footer={
        isSuccess ? undefined : (
          <>
            <DialogButton
              variant="ghost"
              type="button"
              onClick={onClose}
              disabled={isJoining}
            >
              Cancel
            </DialogButton>
            <DialogButton
              variant="primary"
              type="submit"
              form="join-household-form"
              disabled={isJoining || codeValue.length !== 6}
              className="uppercase tracking-wider"
            >
              {isJoining ? "Joining..." : "Join"}
            </DialogButton>
          </>
        )
      }
    >
      {isSuccess ? (
        <div className="flex flex-col items-center justify-center py-6 space-y-4 animate-in zoom-in-95 duration-300">
          <div className="h-16 w-16 rounded-full bg-primary/20 flex items-center justify-center text-primary border border-primary/30 shadow-[0_0_20px_rgba(200,255,0,0.2)]">
            <Check size={32} className="animate-bounce" />
          </div>
          <p className="text-xs text-muted text-center font-body max-w-xs">
            Setting up your workspace dashboard...
          </p>
        </div>
      ) : (
        <form id="join-household-form" onSubmit={handleJoin} className="space-y-6">
          <p className="text-xs text-muted font-body max-w-xs mx-auto text-center">
            Enter the 6-digit invitation code generated by the household owner.
          </p>

          {/* Input Code */}
          <div className="space-y-2">
            <div className="relative">
              <input
                ref={inputRef}
                type="text"
                inputMode="text"
                placeholder="ABC-123"
                value={getDisplayValue()}
                onChange={handleInputChange}
                disabled={isJoining}
                className="w-full bg-background border border-border rounded-[2px] px-4 py-3 text-center font-mono text-xl font-bold tracking-widest text-primary focus:ring-2 focus:ring-primary/40 focus:border-primary outline-none transition-all uppercase placeholder:text-zinc-700"
              />
            </div>

            {errorMsg && (
              <div className="flex items-center gap-2 text-xs font-semibold text-destructive font-body justify-center bg-destructive/10 p-2.5 rounded-[2px] border border-destructive/20">
                <ShieldAlert size={14} className="shrink-0" />
                <span>{errorMsg}</span>
              </div>
            )}
          </div>
        </form>
      )}
    </Dialog>
  );
}
